name: sha_red
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
  build_runner: ^2.5.0
  freezed_annotation: ^3.1.0
  # path: ^1.8.0

dev_dependencies:
  json_serializable: ^6.10.0
  freezed:
  lints: ^5.0.0
  test: ^1.24.0
