enum WsEventToServer {
  newMessage,
  deleteMessage,
  incrementCounter,
  decrementCounter,
  deleteLetter,
  newLetter,
  joinLetters,
  joinCounter,
  leaveRoom,
  listRooms,
  sendLetterToRoom,
  fetchRoomHistory,
  joinAdmin,
}
